### ISSUE TITLE
set "SameSite" to "Strict" for session cookies

### ISSUE THREAD

**Issue by jvantuyl** [petalframework/petal_boilerplate#11]
According to various browser console messages, cookies will very soon need to have the `SameSite` attribute set to deliver cookies across sites.  [Here](https://elixirforum.com/t/how-to-add-samesite-cookies-on-phoenix/31658) is an example of the ones in Chrome (which also includes the solution).  I've also seen these in Firefox as well,

I'm pretty sure there's really no legitimate reason to forward these across sites anyways, so setting this to "strict" just applies the security policy we should probably have anyways.  Best case, more secure.  Worst case, at least we're making the console less noisy for devs.

It looks like all we need to do is append `extra: "SameSite=Strict"` to the `@session_options` [here](https://github.com/petalframework/petal_boilerplate/blob/4a0b3d8ee860215d44aac2bd02893b8013cf26df/lib/petal_boilerplate_web/endpoint.ex#L7-L11).

**Comment by jvantuyl** [comment]
Filed a similar issue on the main Phoenix Project (phoenixframework/phoenix#4877).

**Comment by mplatts** [comment]
Thanks - didn't know about that and not sure whether to set a default. Let's see what happens on your Phoenix issue

**Comment by jvantuyl** [comment]
This ended up merged upstream (https://github.com/phoenixframework/phoenix/pull/4677).  Did this get pulled into Petal?  If it did, can we close this?

**Comment by mplatts** [comment]
Yep seems to be in there
