### ISSUE TITLE
Setup and run errors

### ISSUE THREAD

**Issue by belgoros** [petalframework/petal_boilerplate#22]
Starting the app with `mix phx.server` fails with the below error:
```
petal_boilerplate git:(main) ✗ mix phx.server
Unchecked dependencies for environment dev:
* petal_components (../petal_components)
  the dependency is not available
** (Mix) Can't continue due to errors on dependencies
```

Steps to reproduce:

- cloning the project
- modify the `.tool_versions` file (to match my current versions as follows):
```
erlang 27.0
elixir 1.17.1-otp-27	
```
- modify the `dev.exs` to pint to an existing database:
```
#dev.exs
...
config :petal_boilerplate, PetalBoilerplate.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "calendlex_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
...
```
- run `mix setup`
- run `mix phx.server`
- running `mix deps.get` didn't fix the problem.

**Comment by bitshaker** [comment]
I'm having the same issue.

I'm running in devcontainer on MacOS 14.6.1

**Comment by mitkins** [comment]
I recently updated the boilerplate, this might be a mistake I've introduced. I'll review this when I get a chance

**Comment by bitshaker** [comment]
I manually went in to mix.exs and updated the petal_components dependency as it looks like it was pretty old at 1.0.

Once I updated it to this

`{:petal_components, "~> 2.0.3"},`

things started working with `mix setup`

**Comment by mitkins** [comment]
I added the above solution. Should be working now!
