### ISSUE TITLE
"sed: RE error: illegal byte sequence" when running /rename_phoenix_project.sh

### ISSUE THREAD

**Issue by kimko** [petalframework/petal_boilerplate#4]
**Thx for this project!!**

FYI: I received
```
sed: RE error: illegal byte sequence
```
when running `./rename_phoenix_project.sh`
(macos 11.6.2, arm)

This fixed the issue for me:
```
export LC_CTYPE=C 
export LANG=C
```
https://stackoverflow.com/a/19770395/1977858

❗ I wouldn't recommend putting this into your profile file. Set this only for the command.

**Comment by mplatts** [comment]
Thanks. My bash skills are pretty subpar - would adding 

```
export LC_CTYPE=C 
export LANG=C
```

to the top of the script fix it for other people? Or they have to run it in their terminal themselves?

**Comment by nhobes** [comment]
Thanks, fixed in my latest changes.
