### ISSUE TITLE
Tailwind imports

### ISSUE THREAD

**Issue by samaaron** [petalframework/petal_boilerplate#6]
Hi there,

I'm not experienced enough yet with all this stuff to be sure that a PR is a good idea here, but locally in my `app.css` I had to modify the following:

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

to

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I'm not sure why that was necessary - perhaps I'm using a different version of tailwind? To be clear, I wasn't using this boiler project directly, rather using it as a "cheat sheet" to figure out what to add where.

Anyway, just thought I'd mention it and also say thanks for all the work on this!

**Comment by nhobes** [comment]
Thanks for pointing this out, just updated in my latest changes.
